# fly.toml app configuration file generated for diy-meal-kit on 2026-03-04T12:26:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'diy-meal-kit'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
